WebApplication1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebAplication.BusinessLogics;
using WebAplication.BusinessLogics.Interface;
using WebAplication.Domains.Entities.Response;
using WebAplication.Domains.Entities.User;
using WebApplication1.Models.User;

namespace WebApplication1.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogin _sesion;

        public LoginController()
        {
            var bl = new BussinesLogic();
            _sesion = bl.GetLoginBL();

        }

        public ActionResult Pages_Login()
        {
            return View();
        }

        [HttpPost]          
          public ActionResult Pages_Login(UserData obj_emp)
        {
            var UData = new ULoginData
            {
                UserName = obj_emp.UserName,
                Password = obj_emp.Password,
                LoginDataTime = DateTime.Now,
            };

            ULoginResp resp = _sesion.UserLoginAction(UData);

            if (resp.IsSuccess)
            {
                HttpCookie cookie = _sesion.GenCookie(obj_emp.UserName);
                ControllerContext.HttpContext.Response.Cookies.Add(cookie);

                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult Pages_Lock_Screen()
        {
            return View();
        }

    }
}

WebApplication1/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAplication.BusinessLogics.Interface;
using WebAplication.BusinessLogics;
using WebAplication.Domains.Entities.Response;
using WebAplication.Domains.Entities.User;
using WebApplication1.Models.User;

namespace WebApplication1.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ILogin _sesion;

        public RegisterController()
        {
            var bl = new BussinesLogic();
            _sesion = bl.GetLoginBL();
        }

        // GET: Register
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(UserDataRegist obj_emp)
        {
            var URData = new URegistdata
            {
                UserName = obj_emp.UserName,
                Password = obj_emp.Password,
                Email = obj_emp.Email,
                IP = Request.UserHostAddress,
                LoginDataTime = DateTime.Now,
            };

            ULoginResp resp = _sesion.UserRegistAction(URData);


            return Redirect("/Home/Index");
        }
    }
}

WebApplication1/Views/Register/Index.cshtml
@{
     ViewBag.Title = "Index";
     Layout = "~/Views/Shared/_NotFooterHeader.cshtml";
}

@using (Html.BeginForm("Index", "Register", FormMethod.Post))
{
<div class="account-pages mt-5 mb-5">
     <div class="container">
          <div class="row justify-content-center">
               <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card">

                         <div class="card-body p-4">

                              <div class="text-center w-75 m-auto">
                                   <a href="index.html">
                                        <span><img src="assets/images/logo-light.png" alt="" height="22"></span>
                                   </a>
                                   <p class="text-muted mb-0">Don't have an account?</p>
                                   <p class="text-muted mt-0">Create your own account, it takes less than a minute</p>



                              </div>

                              <form action="#">

                                   <div class="form-group">
                                        <label for="fullname">Full Name</label>
                                        <input class="form-control" type="text" id="fullname" placeholder="Enter your name" name="UserName">
                                   </div>
                                   <div class="form-group">
                                        <label for="emailaddress">Email address</label>
                                        <input class="form-control" type="email" id="emailaddress" required placeholder="Enter your email" name="Email">
                                   </div>
                                   <div class="form-group">
                                        <label for="password">Password</label>
                                        <input class="form-control" type="password" required id="password" placeholder="Enter your password" name="Password">
                                   </div>
                                   
                                   <div class="form-group mb-0 text-center">
                                        <button class="btn btn-primary btn-block" type="submit"> Sign Up </button>
                                   </div>

                              </form>

                            

                         </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                    <div class="row mt-3">
                         <div class="col-12 text-center">
                              <p class="text-muted">
                                   Already have account?  <a href="@Url.Action("Pages_Login", "Login", new { area = "" })" class="text-primary font-weight-medium ml-1">Sign In</a>
                              </p>
                         </div> <!-- end col -->
                    </div>
                    <!-- end row -->

               </div> <!-- end col -->
          </div>
          <!-- end row -->
     </div>
     <!-- end container -->
</div>
<!-- end page -->

}